# This is the stand alone config and assumes you _arent_ using home assistant
# Many of the values that home assistant would automatically populate are
# instead explicitly defined here

substitutions:
  name: "usb-timer1"

esphome:
  name: "${name}"
  project:
    name: spuder.usb-timer
    version: "1.0"

logger:

api:

ota:

wifi:
  ap:
    ssid: "Usb-Timer Fallback Hotspot"
    password: "12345678"

captive_portal:

esp8266:
  board: d1_mini

packages:
  usb-timer: github://spuder/USB-Timer/Firmware/esphome/packages/hardware.yaml

dashboard_import:
  package_import_url: github://spuder/USB-Timer/Firmware/esphome/stand-alone.yaml@main